services:
  dream-league-videprinter:
    build:
      target: development
    image: dream-league-videprinter-development
    container_name: dream-league-videprinter-development
    ports:
      - "3002:3002"
      - "9231:9229"
    volumes:
      - ./src:/home/node/src
      - ./package.json:/home/node/package.json
    networks:
      - dream-league
    environment:
      MONGO_URI: mongodb://mongo:27017
      MONGO_DBNAME: dream-league-videprinter
      MONGO_COLLECTION: goal-events
      MONGO_ENABLED: "true"
      USE_MOCK: ${USE_MOCK:-true}
      LIVE_SCORE_KEY: ${LIVE_SCORE_KEY}
      LIVE_SCORE_SECRET: ${LIVE_SCORE_SECRET}
  mongo:
    image: mongo:7
    container_name: dream-league-videprinter-mongo-dev
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - dream-league

networks:
  dream-league:
    external: true
    name: dream-league

volumes:
  mongo-data:
