services:
  dream-league-videprinter:
    profiles:
      - app
    build:
      context: .
      target: development
    ports:
      - '3002:3002'
      - '9231:9229'
    volumes:
      - ./src:/home/node/src
      - ./package.json:/home/node/package.json
    env_file:
      - .env
    environment:
      MONGO_URI: mongodb://dream-league-videprinter-mongo:27017
    depends_on:
      dream-league-videprinter-mongo:
        condition: service_healthy
    networks:
      - dream-league

  dream-league-videprinter-mongo:
    image: mongo:7
    container_name: dream-league-videprinter-mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
    networks:
      - dream-league
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 3s
      retries: 5

networks:
  dream-league:
    driver: bridge
    name: dream-league

volumes:
  mongo_data:
