services:
  dream-league-videprinter:
    build:
      target: development
    image: dream-league-videprinter-test
    container_name: dream-league-videprinter-test
    command: npm run test
    volumes:
      - ./src:/home/node/src
      - ./test:/home/node/test
      - ./test-output:/home/node/test-output
      - ./package.json:/home/node/package.json
    environment:
      NODE_OPTIONS: "$NODE_OPTIONS --experimental-vm-modules"
